version: '3.8'

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ads_tracker
            DB_USERNAME: root
            DB_PASSWORD: root
        command: sh -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=8000"

    db:
        image: mysql:8.2
        container_name: mysql_container
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ads_tracker
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
